apiVersion: v1
kind: Namespace
metadata:
  name: push-system
  labels:
    name: push-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: push-server-config
  namespace: push-system
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      }
    }
